version: '3.8'
services:
  client:
    image: client-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: client-prod-c
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
